//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.14 at 11:25:16 AM BRT 
//


package br.com.ttrans.samapp.ws.bo.alarm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.ttrans.samapp.ws.bo.alarm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.ttrans.samapp.ws.bo.alarm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AlarmDeleteRequest }
     * 
     */
    public AlarmDeleteRequest createAlarmDeleteRequest() {
        return new AlarmDeleteRequest();
    }

    /**
     * Create an instance of {@link AlarmBase }
     * 
     */
    public AlarmBase createAlarmBase() {
        return new AlarmBase();
    }

    /**
     * Create an instance of {@link AlarmAllCurrentRequest }
     * 
     */
    public AlarmAllCurrentRequest createAlarmAllCurrentRequest() {
        return new AlarmAllCurrentRequest();
    }

    /**
     * Create an instance of {@link AlarmDetail }
     * 
     */
    public AlarmDetail createAlarmDetail() {
        return new AlarmDetail();
    }

    /**
     * Create an instance of {@link AlarmRequestAckRequest }
     * 
     */
    public AlarmRequestAckRequest createAlarmRequestAckRequest() {
        return new AlarmRequestAckRequest();
    }

    /**
     * Create an instance of {@link AlarmUpdateStateRequest }
     * 
     */
    public AlarmUpdateStateRequest createAlarmUpdateStateRequest() {
        return new AlarmUpdateStateRequest();
    }

    /**
     * Create an instance of {@link AlarmRequestAllRequest }
     * 
     */
    public AlarmRequestAllRequest createAlarmRequestAllRequest() {
        return new AlarmRequestAllRequest();
    }

    /**
     * Create an instance of {@link AlarmAddRequest }
     * 
     */
    public AlarmAddRequest createAlarmAddRequest() {
        return new AlarmAddRequest();
    }

    /**
     * Create an instance of {@link MessageParams }
     * 
     */
    public MessageParams createMessageParams() {
        return new MessageParams();
    }

    /**
     * Create an instance of {@link AlarmRefreshRequest }
     * 
     */
    public AlarmRefreshRequest createAlarmRefreshRequest() {
        return new AlarmRefreshRequest();
    }

}
