//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.14 at 11:24:38 AM BRT 
//


package br.com.ttrans.samapp.ws.bo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.ttrans.samapp.ws.bo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.ttrans.samapp.ws.bo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnectionRequest() {
        return new Connection();
    }

    /**
     * Create an instance of {@link SessionDetailRequest }
     * 
     */
    public SessionDetailRequest createSessionDetailRequest() {
        return new SessionDetailRequest();
    }

    /**
     * Create an instance of {@link ActiveRequest }
     * 
     */
    public ActiveRequest createActiveRequest() {
        return new ActiveRequest();
    }

    /**
     * Create an instance of {@link DisconnectionRequest }
     * 
     */
    public DisconnectionRequest createDisconnectionRequest() {
        return new DisconnectionRequest();
    }

    /**
     * Create an instance of {@link AliveRequest }
     * 
     */
    public AliveRequest createAliveRequest() {
        return new AliveRequest();
    }

}
