/* Table:		SITES
 * Prefix:		SIT
 * Date:		03/11/2014
 * Author:		Joabe Lucena
 * References:	SITES(SIT_ID),SITES_TYPE(STY_ID), SERVICE_STATION(SST_ID)
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SITES (
  SIT_ID			INT			NOT NULL	PRIMARY KEY
  ,SIT_DESCRIPTION	VARCHAR(45) NOT NULL
  ,SIT_SHORTNAME	VARCHAR(15) NOT NULL
  ,SIT_STATION_ID	INT			NOT NULL
  ,SIT_PARENT_ID	INT
  ,SIT_TYPE_ID		INT			NOT NULL
  ,USR_INSERT		VARCHAR(45)	NOT NULL
  ,DTI_INSERT		TIMESTAMP	NOT NULL
  ,USR_UPDATE		VARCHAR(45)
  ,DTI_UPDATE		TIMESTAMP);
COMMIT;


/*INDEXES*/
CREATE INDEX fk_SIT_STY_idx ON SITES(SIT_TYPE_ID);
CREATE INDEX fk_SIT_SIT_idx ON SITES(SIT_PARENT_ID);
CREATE INDEX fk_SIT_SST_idx ON SITES(SIT_STATION_ID);
CREATE INDEX ix_SIT_INDEX1_idx ON SITES(SIT_DESCRIPTION);


/*REFERENCES*/
ALTER TABLE SITES
ADD CONSTRAINT fk_SIT_SIT_ref
    FOREIGN KEY (SIT_PARENT_ID)
    REFERENCES SITES (SIT_ID),
    
ADD CONSTRAINT fk_SIT_STY_ref
    FOREIGN KEY (SIT_TYPE_ID)
    REFERENCES SITES_TYPE (STY_ID),
    
ADD CONSTRAINT fk_SIT_SST_ref
    FOREIGN KEY (SIT_STATION_ID)
    REFERENCES SERVICE_STATION (SST_ID);
    

/*GENERATOR*/
CREATE GENERATOR GEN_SIT_ID;
SET GENERATOR GEN_SIT_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SIT_ID  FOR SITES ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SIT_ID IS NULL)
        then new.SIT_ID = GEN_ID(GEN_SIT_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SIT_LOG  FOR SITES ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;

/******* END OF TABLE CONFIG *******/

