/* Table:		SEVERITY_LEVEL
 * Prefix:		SLE
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SEVERITY_LEVEL (
  SLE_ID			INT			NOT NULL PRIMARY KEY,
  SLE_DESCRIPTION	VARCHAR(45) NOT NULL,
  SLE_DISPLAY_COLOR VARCHAR(7)	NOT NULL,
  SLE_TIME_SERVICE	INT			NOT NULL,
  USR_INSERT		VARCHAR(45) NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP,
  DELETED			CHAR(1)		DEFAULT '');
COMMIT;

/*INDEXES*/
CREATE INDEX ix_SLE_INDEX1_idx ON SEVERITY_LEVEL(SLE_DESCRIPTION);


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SLE_LOG  FOR SEVERITY_LEVEL ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;

/*POPULATE TABLE*/
INSERT INTO SEVERITY_LEVEL(SLE_ID,SLE_DESCRIPTION,SLE_DISPLAY_COLOR,SLE_TIME_SERVICE,USR_INSERT)VALUES(0,'-'		,'#000000',60,'SYSTEM');
INSERT INTO SEVERITY_LEVEL(SLE_ID,SLE_DESCRIPTION,SLE_DISPLAY_COLOR,SLE_TIME_SERVICE,USR_INSERT)VALUES(1,'NORMAL'	,'#000000',60,'SYSTEM');
INSERT INTO SEVERITY_LEVEL(SLE_ID,SLE_DESCRIPTION,SLE_DISPLAY_COLOR,SLE_TIME_SERVICE,USR_INSERT)VALUES(2,'LEVE'		,'#000000',60,'SYSTEM');
INSERT INTO SEVERITY_LEVEL(SLE_ID,SLE_DESCRIPTION,SLE_DISPLAY_COLOR,SLE_TIME_SERVICE,USR_INSERT)VALUES(3,'GRAVE'	,'#000000',60,'SYSTEM');
/******* END OF TABLE CONFIG *******/

