/* Table:		DOCUMENTS_TYPE
 * Prefix:		DTY
 * Date:		17/03/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE DOCUMENTS_TYPE (
  DTY_ID			INT			PRIMARY KEY,
  DTY_DESCRIPTION	VARCHAR(45) NOT NULL,
  DTY_EXTENSION		VARCHAR(10) NOT NULL,
  USR_INSERT		VARCHAR(45) NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP,
  DELETED			CHAR(1)		DEFAULT '');
COMMIT;

/*INDEXES*/

/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_DTY_ID;
SET GENERATOR GEN_DTY_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_DTY_ID  FOR DOCUMENTS_TYPE ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.DTY_ID IS NULL)
        then new.DTY_ID = GEN_ID(GEN_DTY_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_DTY_LOG  FOR DOCUMENTS_TYPE ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

