/* Table:		DOCUMENTS
 * Prefix:		DOC
 * Date:		17/03/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE DOCUMENTS (
  DOC_ID			INT			NOT NULL,
  DOC_TYPE_ID		INT			NOT NULL,
  DOC_EQUIPMENT_ID	VARCHAR(20)	NOT NULL,
  DOC_DESCRIPTION	VARCHAR(45)	NOT NULL,
  DOC_URL			VARCHAR(45)	NOT NULL,
  USR_INSERT		VARCHAR(45)	NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP,
  PRIMARY KEY (DOC_ID, DOC_TYPE_ID, DOC_EQUIPMENT_ID));
COMMIT;
  

/*INDEXES*/
CREATE INDEX fk_DOC_EQU_idx ON DOCUMENTS(DOC_EQUIPMENT_ID);
CREATE INDEX fk_DOC_DTY_idx ON DOCUMENTS(DOC_TYPE_ID);

/*REFERENCES*/
ALTER TABLE DOCUMENTS
ADD CONSTRAINT fk_DOC_EQU_ref
    FOREIGN KEY (DOC_EQUIPMENT_ID)
    REFERENCES EQUIPMENTS (EQU_ID),
ADD CONSTRAINT fk_DOC_DTY_ref
    FOREIGN KEY (DOC_TYPE_ID)
    REFERENCES DOCUMENTS_TYPE (DTY_ID);
    
/*GENERATOR*/
CREATE GENERATOR GEN_DOC_ID;
SET GENERATOR GEN_DOC_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_DOC_ID  FOR DOCUMENTS ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.DOC_ID IS NULL)
        then new.DOC_ID = GEN_ID(GEN_DOC_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_DOC_LOG  FOR DOCUMENTS ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

