/* Table:		ALARMS
 * Prefix:		ALM
 * Date:		03/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:			Not Incremental ID
 * */

/*TABLE*/
CREATE TABLE ALARMS (
  ALM_ID			VARCHAR(20) NOT NULL PRIMARY KEY
  ,ALM_DESCRIPTION	VARCHAR(45) NOT NULL
  ,ALM_NORM_ID		VARCHAR(20)
  ,ALM_NORM_MAN		CHAR(1)		NOT NULL
  ,ALM_NORM_ALM		CHAR(1)		NOT NULL
  ,ALM_GROUP_ID		INT			NOT NULL
  ,ALM_TYPE_ID		INT			NOT NULL
  ,ALM_MODEL_ID		INT			NOT NULL
  ,ALM_SEVERITY_ID	VARCHAR(2)	NOT NULL
  ,USR_INSERT		VARCHAR(45) NOT NULL
  ,DTI_INSERT		TIMESTAMP	NOT NULL
  ,USR_UPDATE		VARCHAR(45) 
  ,DTI_UPDATE		TIMESTAMP);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_ALM_AGR_idx ON ALARMS(ALM_GROUP_ID);
CREATE INDEX fk_ALM_ATY_idx ON ALARMS(ALM_TYPE_ID);
CREATE INDEX ix_ALM_INDEX1_idx ON ALARMS(ALM_DESCRIPTION);
CREATE INDEX fk_ALM_EMO_idx ON ALARMS(ALM_MODEL_ID);
CREATE INDEX fk_ALM_ALM_idx ON ALARMS(ALM_NORM_ID);
CREATE INDEX fk_ALM_SLE_idx ON ALARMS(ALM_SEVERITY_ID);

/*REFERENCES*/
ALTER TABLE ALARMS
ADD CONSTRAINT fk_ALM_AGR_ref
    FOREIGN KEY (ALM_GROUP_ID)
    REFERENCES ALARMS_GROUP (AGR_ID),
    
ADD CONSTRAINT fk_ALM_ATY_ref
    FOREIGN KEY (ALM_TYPE_ID)
    REFERENCES ALARMS_TYPE (ATY_ID),
    
ADD CONSTRAINT fk_ALM_EMO_ref
    FOREIGN KEY (ALM_MODEL_ID)
    REFERENCES EQUIPMENTS_MODEL (EMO_ID),
    
ADD CONSTRAINT fk_ALM_ALM_ref
    FOREIGN KEY (ALM_NORM_ID)
    REFERENCES ALARMS (ALM_ID),
    
ADD CONSTRAINT fk_ALM_SLE_ref
    FOREIGN KEY (ALM_SEVERITY_ID)
    REFERENCES SEVERITY_LEVEL (SLE_ID);

  
/*GENERATOR*/

/*TRIGGER ID*/

    
/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_ALM_LOG  FOR ALARMS ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

