/* Table:		SERVICE_ORDER_TYPE
 * Prefix:		SOT
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SERVICE_ORDER_TYPE (
  SOT_ID INT NOT NULL PRIMARY KEY,
  SOT_DESCRIPTION VARCHAR(45) NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45) ,
  DTI_UPDATE TIMESTAMP ,
  DELETED CHAR(1) DEFAULT '');
COMMIT;

/*INDEXES*/
CREATE INDEX ix_SOT_INDEX1_idx ON SERVICE_ORDER_TYPE(SOT_DESCRIPTION);  
/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_SOT_ID;
SET GENERATOR GEN_SOT_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOT_ID  FOR SERVICE_ORDER_TYPE ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SOT_ID IS NULL)
        then new.SOT_ID = GEN_ID(GEN_SOT_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOT_LOG  FOR SERVICE_ORDER_TYPE ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

