/* Table:		SERVICE_ORDER_STATUS
 * Prefix:		SOS
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SERVICE_ORDER_STATUS (
  SOS_ID			INT			NOT NULL PRIMARY KEY,
  SOS_DESCRIPTION	VARCHAR(45) NOT NULL,
  SOS_FEAT_ID		INT,
  SOS_LOG_REMARK	CHAR(1)		NOT NULL,
  USR_INSERT		VARCHAR(45) NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP);
COMMIT;

/*INDEXES*/
CREATE INDEX ix_SOS_INDEX1_idx ON SERVICE_ORDER_STATUS(SOS_DESCRIPTION);

/*REFERENCES*/
ALTER TABLE SERVICE_ORDER_STATUS
ADD CONSTRAINT fk_SOS_FEAT_ref
    FOREIGN KEY (SOS_FEAT_ID)
    REFERENCES SYS_FEATURES (ID);

/*GENERATOR*/
CREATE GENERATOR GEN_SOS_ID;
SET GENERATOR GEN_SOS_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOS_ID  FOR SERVICE_ORDER_STATUS ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SOS_ID IS NULL)
        then new.SOS_ID = GEN_ID(GEN_SOS_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOS_LOG  FOR SERVICE_ORDER_STATUS ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;



/*POPULATE TABLE*/

-- RELATED FEATURES
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Abrir'				, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Atribuir Técnico'	, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Analisar'			, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Solic. Troca Téc.'	, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Solicitar Aut.'		, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Rejeitar'			, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Reabrir'				, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Liberar Acesso'		, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Iniciar Atend.'		, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Interr. Atend.'		, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Concluir Atend.'		, null);
INSERT INTO SYS_FEATURES(DESCRIPTION,URL) VALUES ('Finalizar'			, null);

INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('NOVA'						,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Abrir')				);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('ATRIBUIDA'				,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Atribuir Técnico')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('EM ANALISE'				,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Analisar')			);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('REATRIBUIR'				,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Solic. Troca Téc.')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('REJEITADO'				,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Rejeitar')			);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('AGUARDANDO AUTORIZACAO'	,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Solicitar Aut')		);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('ACESSO LIBERADO'			,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Liberar Acesso')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('EM ANDAMENTO'				,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Iniciar Atend.')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('EM ESPERA'				,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Interr. Atend.')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('CONCLUIDO'				,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Concluir Atend.')	);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('FINALIZADO'				,'SYSTEM','N',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Finalizar')			);
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT,SOS_LOG_REMARK,SOS_FEAT_ID) VALUES ('REABERTO'					,'SYSTEM','Y',(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reabrir')			);

/******* END OF TABLE CONFIG *******/

