/* Table:		SERVICE_ORDER_STATUS
 * Prefix:		SOS
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SERVICE_ORDER_STATUS (
  SOS_ID INT NOT NULL PRIMARY KEY,
  SOS_DESCRIPTION VARCHAR(45) NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45),
  DTI_UPDATE TIMESTAMP,
  DELETED CHAR(1) DEFAULT '');
COMMIT;

/*INDEXES*/
CREATE INDEX ix_SOS_INDEX1_idx ON SERVICE_ORDER_STATUS(SOS_DESCRIPTION);

/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_SOS_ID;
SET GENERATOR GEN_SOS_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOS_ID  FOR SERVICE_ORDER_STATUS ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SOS_ID IS NULL)
        then new.SOS_ID = GEN_ID(GEN_SOS_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOS_LOG  FOR SERVICE_ORDER_STATUS ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;

/*POPULATE TABLE*/
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('NOVA','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('ATRIBUIDA','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('EM ANALISE','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('REATRIBUIR','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('REJEITADO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('AGUARDANDO AUTORIZACAO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('ACESSO LIBERADO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('EM ANDAMENTO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('EM ESPERA','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('CONCLUIDO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('FINALIZADO','SYSTEM');
INSERT INTO SERVICE_ORDER_STATUS (SOS_DESCRIPTION,USR_INSERT) VALUES ('REABERTO','SYSTEM');

/******* END OF TABLE CONFIG *******/

