/* Table:		TECHNICIAN
 * Prefix:		TEC
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:			Not Incremental ID
 * */

/*TABLE*/
CREATE TABLE TECHNICIAN (
  TEC_ID VARCHAR(6) NOT NULL PRIMARY KEY,
  TEC_NAME VARCHAR(45) NOT NULL,
  TEC_SITE_ID INT NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45),
  DTI_UPDATE TIMESTAMP,
  DELETED CHAR(1) DEFAULT '');
COMMIT;

/*INDEXES*/
CREATE INDEX fk_TEC_SIT_idx ON TECHNICIAN(TEC_SITE_ID);
CREATE INDEX ix_TEC_INDEX1_idx ON TECHNICIAN(TEC_NAME);
  
/*REFERENCES*/
ALTER TABLE TECHNICIAN
ADD CONSTRAINT fk_TEC_SIT_ref
    FOREIGN KEY (TEC_SITE_ID)
    REFERENCES SITES (SIT_ID);

/*GENERATOR*/

/*TRIGGER ID*/

/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_TEC_LOG  FOR TECHNICIAN ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

