/* Table:		SERVICE_ORDER
 * Prefix:		SOR
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	SERVICE_ORDER_TYPE (SOT_ID),SERVICE_ORDER_STATUS (SOS_ID)
 * 				EVENTS (EVE_ID),SERVICE_ORDER (SOR_ID),EQUIPMENTS (EQU_ID)
 * Obs:			
 * */

/*TABLE*/
CREATE TABLE SERVICE_ORDER (
   SOR_ID				INT			NOT NULL PRIMARY KEY
  ,SOR_TYPE_ID			INT			NOT NULL
  ,SOR_STATUS_ID		INT			NOT NULL
  ,SOR_EVENT_ID			BIGINT
  ,SOR_PARENT_ID		INT
  ,SOR_TECHNICIAN_ID	VARCHAR(6)
  ,SOR_START_FORECAST	TIMESTAMP	NOT NULL
  ,SOR_START			TIMESTAMP 
  ,SOR_END_FORECAST		TIMESTAMP	NOT NULL
  ,SOR_END				TIMESTAMP 
  ,SOR_PRIORITY_ID		VARCHAR(2)	NOT NULL
  ,SOR_REMARKS			CHAR(255)
  ,SOR_EQUIPMENT_ID		VARCHAR(20) NOT NULL
  ,SOR_EQUIPMENT_STOP	CHAR(1)		NOT NULL
  ,USR_INSERT			VARCHAR(45)	NOT NULL
  ,DTI_INSERT			TIMESTAMP	NOT NULL
  ,USR_UPDATE			VARCHAR(45) 
  ,DTI_UPDATE			TIMESTAMP);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_SOR_SOT_idx ON SERVICE_ORDER(SOR_TYPE_ID);
CREATE INDEX fk_SOR_SOS_idx ON SERVICE_ORDER(SOR_STATUS_ID);
CREATE INDEX fk_SOR_EVE_idx ON SERVICE_ORDER(SOR_EVENT_ID);
CREATE INDEX fk_SOR_SOR_idx ON SERVICE_ORDER(SOR_PARENT_ID);
CREATE INDEX fk_SOR_EQU_idx ON SERVICE_ORDER(SOR_EQUIPMENT_ID);
CREATE INDEX fk_SOR_SLE_idx ON SERVICE_ORDER(SOR_PRIORITY_ID);
CREATE INDEX fk_SOR_TEC_idx ON SERVICE_ORDER(SOR_TECHNICIAN_ID);


/*REFERENCES*/
ALTER TABLE SERVICE_ORDER
ADD CONSTRAINT fk_SOR_SOT_ref
    FOREIGN KEY (SOR_TYPE_ID)
    REFERENCES SERVICE_ORDER_TYPE (SOT_ID),

ADD CONSTRAINT fk_SOR_SOS_ref
    FOREIGN KEY (SOR_STATUS_ID)
    REFERENCES SERVICE_ORDER_STATUS (SOS_ID),

ADD CONSTRAINT fk_SOR_EVE_ref
    FOREIGN KEY (SOR_EVENT_ID)
    REFERENCES EVENTS (EVE_ID),

ADD CONSTRAINT fk_SOR_SOR_ref
    FOREIGN KEY (SOR_PARENT_ID)
    REFERENCES SERVICE_ORDER (SOR_ID),

ADD CONSTRAINT fk_SOR_EQU_ref
    FOREIGN KEY (SOR_EQUIPMENT_ID)
    REFERENCES EQUIPMENTS (EQU_ID),

ADD CONSTRAINT fk_SOR_SLE_ref
    FOREIGN KEY (SOR_PRIORITY_ID)
    REFERENCES SEVERITY_LEVEL (SLE_ID),

ADD CONSTRAINT fk_SOR_TEC_ref
    FOREIGN KEY (SOR_TECHNICIAN_ID)
    REFERENCES TECHNICIAN (TEC_ID);
    
/*GENERATOR*/
CREATE GENERATOR GEN_SOR_ID;
SET GENERATOR GEN_SOR_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOR_ID  FOR SERVICE_ORDER ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SOR_ID IS NULL)
        then new.SOR_ID = GEN_ID(GEN_SOR_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOR_LOG  FOR SERVICE_ORDER ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

