/*
 * Variaveis:
 * STATUS_RULES:	Tabela
 * SRU:	Prefixo da Tabela
 * SRU_ID:	Campo ID da Tabela
 * */

/* Table:		STATUS_RULES
 * Prefix:		SRU
 * Date:		04/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE STATUS_RULES (
  SRU_ID			INT			NOT NULL PRIMARY KEY,
  SRU_ROLE_ID		INT			NOT NULL,
  SRU_CUR_STATUS_ID INT			NOT NULL,
  SRU_NXT_STATUS_ID INT			NOT NULL,
  SRU_LOG_REMARK	CHAR(1)		NOT NULL,
  USR_INSERT		VARCHAR(45) NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP,
  DELETED			CHAR(1)		DEFAULT '');
COMMIT;
  

/*INDEXES*/
CREATE INDEX fk_SRU_ROLE_idx ON STATUS_RULES(SRU_ROLE_ID);
CREATE INDEX fk_SRU_SOS_A_idx ON STATUS_RULES(SRU_CUR_STATUS_ID);
CREATE INDEX fk_SRU_SOS_B_idx ON STATUS_RULES(SRU_NXT_STATUS_ID);

/*REFERENCES*/
ALTER TABLE STATUS_RULES
ADD CONSTRAINT fk_SRU_ROLE_ref
    FOREIGN KEY (SRU_ROLE_ID)
    REFERENCES ROLE (id),

ADD CONSTRAINT fk_SRU_SOS_A_ref
    FOREIGN KEY (SRU_CUR_STATUS_ID)
    REFERENCES SERVICE_ORDER_STATUS (SOS_ID),

ADD CONSTRAINT fk_SRU_SOS_B_ref
    FOREIGN KEY (SRU_NXT_STATUS_ID)
    REFERENCES SERVICE_ORDER_STATUS (SOS_ID);
  
  
/*GENERATOR*/
CREATE GENERATOR GEN_SRU_ID;
SET GENERATOR GEN_SRU_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SRU_ID  FOR STATUS_RULES ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SRU_ID IS NULL)
        then new.SRU_ID = GEN_ID(GEN_SRU_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SRU_LOG  FOR STATUS_RULES ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;

/*POPULATE TABLE*/
-- STATUS: 1
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,'SYSTEM');
	
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,'SYSTEM');

-- STATUS: 2
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'NOVA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

-- STATUS: 3
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

-- STATUS: 4
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,'SYSTEM');
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,'SYSTEM');
	
-- STATUS: 5
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REJEITADO')
	,'SYSTEM');
	
-- STATUS: 5.1
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REJEITADO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REJEITADO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,'SYSTEM');

-- STATUS: 6
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ATRIBUIDA')
	,'SYSTEM');

-- STATUS: 7
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'AGUARDANDO AUTORIZACAO')
	,'SYSTEM');

-- STATUS: 8
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'AGUARDANDO AUTORIZACAO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ACESSO LIBERADO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'AGUARDANDO AUTORIZACAO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ACESSO LIBERADO')
	,'SYSTEM');

-- STATUS: 9
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'ACESSO LIBERADO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,'SYSTEM');

-- STATUS: 10
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ESPERA')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ESPERA')
	,'SYSTEM');

-- STATUS: 11
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ESPERA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ESPERA')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,'SYSTEM');

-- STATUS: 12
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANDAMENTO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,'SYSTEM');

-- STATUS: 13
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,'SYSTEM');
	
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REABERTO')
	,'SYSTEM');
	
-- STATUS: 14
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'FINALIZADO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'CONCLUIDO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'FINALIZADO')
	,'SYSTEM');

-- STATUS: 15
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REJEITADO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'FINALIZADO')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REJEITADO')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'FINALIZADO')
	,'SYSTEM');

-- STATUS: 16
INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,'SYSTEM');

INSERT INTO STATUS_RULES (SRU_ROLE_ID,SRU_LOG_REMARK,SRU_CUR_STATUS_ID,SRU_NXT_STATUS_ID,USR_INSERT)
VALUES
	((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE')
	,'S'
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'EM ANALISE')
	,(SELECT SOS_ID FROM SERVICE_ORDER_STATUS WHERE SOS_DESCRIPTION = 'REATRIBUIR')
	,'SYSTEM');


/******* END OF TABLE CONFIG *******/

