/* Table:		SERVICE_ORDER_FORECAST
 * Prefix:		SOF
 * Date:		03/03/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE SERVICE_ORDER_FORECAST(
	SOF_ID				INT			NOT NULL PRIMARY KEY,
	SOF_SEVERITY_ID		VARCHAR(2)	NOT NULL,
	SOF_SUB_SYSTEM_ID	VARCHAR(10) NOT NULL,
	SOF_START_FORECAST	INT			NOT NULL,
	SOF_END_FORECAST	INT			NOT NULL,
	USR_INSERT			VARCHAR(45) NOT NULL,
	DTI_INSERT			TIMESTAMP	NOT NULL,
	USR_UPDATE			VARCHAR(45),
	DTI_UPDATE			TIMESTAMP,
	DELETED				CHAR(1)		DEFAULT ''
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_SOF_SLE_idx ON SERVICE_ORDER_FORECAST(SOF_SEVERITY_ID);
CREATE INDEX fk_SOF_SSY_idx ON SERVICE_ORDER_FORECAST(SOF_SUB_SYSTEM_ID);
  
/*REFERENCES*/
ALTER TABLE SERVICE_ORDER_FORECAST
ADD CONSTRAINT fk_SOF_SLE_ref
    FOREIGN KEY (SOF_SEVERITY_ID)
    REFERENCES SEVERITY_LEVEL (SLE_ID),
    
ADD CONSTRAINT fk_SOF_SSY_ref
    FOREIGN KEY (SOF_SUB_SYSTEM_ID)
    REFERENCES SUB_SYSTEM (SSY_ID);
  
/*GENERATOR*/
CREATE GENERATOR GEN_SOF_ID;
SET GENERATOR GEN_SOF_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOF_ID  FOR SERVICE_ORDER_FORECAST ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.SOF_ID IS NULL)
        then new.SOF_ID = GEN_ID(GEN_SOF_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SOF_LOG  FOR SERVICE_ORDER_FORECAST ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/
