/* Table:		ALARM_COUNTER
 * Prefix:		ACO
 * Date:		17/06/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE ALARM_COUNTER (
  ACO_ALARM_ID		VARCHAR(20)	NOT NULL,
  ACO_EQUIPMENT_ID	VARCHAR(20)	NOT NULL,
  ACO_COUNTER		INT			DEFAULT 0,
  ACO_LAST_RESET	TIMESTAMP,
  PRIMARY KEY (ACO_ALARM_ID, ACO_EQUIPMENT_ID)
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_ACO_EQU_idx ON ALARM_COUNTER(ACO_EQUIPMENT_ID);
CREATE INDEX fk_ACO_ALM_idx ON ALARM_COUNTER(ACO_ALARM_ID);

/*REFERENCES*/
ALTER TABLE ALARM_COUNTER
ADD CONSTRAINT fk_ACO_ALM_ref
    FOREIGN KEY (ACO_ALARM_ID)
    REFERENCES ALARMS (ALM_ID),
ADD CONSTRAINT fk_ACO_EQU_ref
    FOREIGN KEY (ACO_EQUIPMENT_ID)
    REFERENCES EQUIPMENTS (EQU_ID);

COMMIT;

/******* END OF TABLE CONFIG *******/