/* Table:		TASK_MONITOR_EQUIPMENTS
 * Prefix:		TME
 * Date:		09/11/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */


/*TABLE*/
CREATE TABLE TASK_MONITOR_EQUIPMENTS (
  TME_ID			INT			NOT NULL PRIMARY KEY,
  TME_TASK_ID		INT,
  TME_EQUIPMENT_ID	VARCHAR(20),
  TME_CUTOFF_DATE	TIMESTAMP
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_TME_EQU_idx ON TASK_MONITOR_EQUIPMENTS(TME_EQUIPMENT_ID);
CREATE INDEX fk_TME_THM_idx ON TASK_MONITOR_EQUIPMENTS(TME_TASK_ID);


/*REFERENCES*/
ALTER TABLE TASK_MONITOR_EQUIPMENTS
ADD CONSTRAINT fk_TME_THM_ref
    FOREIGN KEY (TME_TASK_ID)
    REFERENCES TASK_MONITOR_HEADER (TMH_ID),
    
ADD CONSTRAINT fk_TME_EQU_ref
    FOREIGN KEY (TME_EQUIPMENT_ID)
    REFERENCES EQUIPMENTS (EQU_ID);


/*GENERATOR*/
CREATE GENERATOR GEN_TME_ID;
SET GENERATOR GEN_TME_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_TME_ID  FOR TASK_MONITOR_EQUIPMENTS ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.TME_ID IS NULL)
        then new.TME_ID = GEN_ID(GEN_TME_ID,1);
END^
SET TERM ; ^
COMMIT;

/******* END OF TABLE CONFIG *******/

