/* 
 * Table:	USERS
 */


-- Usuários
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('sam_oper004','f7e72dc5f0a5178209478738798a7e99','ACTIVE',(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));


-- ACESSOS POR PERFIL
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reconhecer Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'CCO')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Normalizar Eventos'));

INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE BARREIROS')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reconhecer Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE BARREIROS')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Normalizar Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE VALONGO')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reconhecer Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'BASE VALONGO')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Normalizar Eventos'));

INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BARREIROS)')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reconhecer Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BARREIROS)')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Normalizar Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (VALONGO)')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Reconhecer Eventos'));
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) VALUES (((SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (VALONGO)')),(SELECT ID FROM SYS_FEATURES WHERE DESCRIPTION = 'Normalizar Eventos'));


/** SETA DIREITOS PERFIL CCO **/

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Inicio'				AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço'	AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Cadastros'			AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Manutenção'			AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Relatórios'			AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'CCO'));


/** SETA DIREITOS PERFIL DAS BASES **/

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Inicio'				AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE BARREIROS'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço'	AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE BARREIROS'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Relatórios'			AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE BARREIROS'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Inicio'				AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE VALONGO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço'	AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE VALONGO'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Relatórios'			AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE VALONGO'));


/** SETA DIREITOS PERFIL DAS OPERAÇÕES **/

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Inicio'				AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BARREIROS)'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço'	AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BARREIROS)'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Inicio'				AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (VALONGO)'));
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES((SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço'	AND PARENT_ID IS NULL),(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (VALONGO)'));

COMMIT;

/** END OF TABLE POPULATION **/


