/* 
 * Table:	EQUIPMENTS_MANUFACTURER
 */
 
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('SIEMENS', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('LENOVO', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('MICROPROCESSADOR', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('PENTON', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('ASL', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('IBM', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('HUAWEI', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('FORTINET', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('WESTERSTRAND', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('HP', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('CISCO', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('TIPRO', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('SEPURA', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('GTEC', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('THALES', 'SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION, USR_INSERT)VALUES('TTRANS', 'SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/


