/* 
 * Table:	EQUIPMENTS_PROTOCOL
 */

INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv1'						,'SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv2c'					,'SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv3'						,'SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES SOAP 1.1'		,'SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES JSON'			,'SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES SOAP MAESTRO'	,'SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/


