/* 
 * Table:	EQUIPMENTS_MODEL
 */

INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('OPENSTAGE 15',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HIPATH4000 DSCXL2',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HIPATH4000 STMI4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THINKCENTRE M73E SFF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PPP.8.96A9RDF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PPP.TFT.32.A2.SF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('CAD10/TEN ',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ANS04',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IPA400',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BMB01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('RCS5FT/ENC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PH20/TC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('MPS01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('X3250 M4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('X3530 M4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('V3700',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SYSTEM DIRECTOR',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('S7703',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('S5700-28C-PWR-SI',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('FORTIGATE 100 D',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('E591B',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ESP30D/2BX',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('QW-TIME III',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('LUMEX 7 NTP POE - 190022-02',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('LUMEX 7 NTP POE - 190020-02',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HP ML350 GEN8',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('2911',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HP ELITE',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HP PROBOOK',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TIPRO BF10',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SOLO',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('AK-160N',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('STP9138',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TH-2CD893PF-E',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TH-2DF1-514',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TH-9616NI-ST',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('DS-3D01R-A',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('VLT VOSSLOH',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('AZLM',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('CVS24',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IOLOGIK E1200',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('LD-120P',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('VLT',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('CATENÁRIA',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');


COMMIT;

/** END OF TABLE POPULATION **/


