/* 
 * Table:	EQUIPMENTS_MODEL
 */

INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BE ESPECIAL FLAP',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BLOQUEIO TRIPE SMART',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('DCE FLAP SMART',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/


