/*** EQUIPMENTS MODELS SCS ***/

INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BUC 500',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BIU 500',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BME 240',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BDV 5000',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BRF CC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BGS 24',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('GVT 500',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('GVT 501',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BNB 5000',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('EFI/EFF 01AS 01BS SC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('BBB',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');

COMMIT;

