/* 
 * Table:	EQUIPMENTS_MODEL
 */


INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS HiPath4000',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS OPENSTAGE 15',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS DIUT2',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS STMI4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS PSU',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS LUNA',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS DSCXL2',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SEPURA SOLO',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HP ML350pGen8',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('CISCO 2911',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('GTEC AK-160N',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND QW-TIME III',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND LUMEX 7',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND E591B',NULL,'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND ESP30D/2BX',NULL,'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HUAWEI S7703',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HUAWEI S5700-28C-PWR-SI',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('FORTIGATE 100 D',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IBM x3250 M4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IBM v3700',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('LENOVO ThinkCentre m73e SFF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('MICROPROCESSADOR PPP.8.96A9RDF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('MICROPROCESSADOR PPP.TFT.32.A2.SF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON CAD10/TEN',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON RCS5FT/ENC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON PH20/TC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL ANS04',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL iPA400',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL BMB01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL MPS01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-2CD893PF-E',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-2DF1-514',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-9616NI-ST',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES DS-3D01R-A',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS BLOQUEIO TRIPE SMART BTS',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS BE ESPECIAL FLAP BEF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS DCE FLAP SMART DCFS',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');




/** END OF TABLE POPULATION **/


