/* 
 * Table:	EQUIPMENTS_TYPE
 */

INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('TELEFONE IP','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SERVIDOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('WORKSTATION','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL LED','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MONITOR TFT','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE PROJEÇÃO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SENSOR DE RUÍDO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MATRIZ DE ÁUDIO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('INTERFACE DE I/O','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE TETO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE CORNETA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MICROFONE MODULAR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('STORAGE','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MÁQUINA VIRTUAL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ROUTER','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ACESSO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('FIREWALL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ANTENA RECEPTORA GPS','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PROTECÇÃO CONTRA RAIOS','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO MESTRE','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE DUPLA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE SIMPLES','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('DISPATCHER SERVER','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ROTEADOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('LAPTOP','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONSOLE DE OPERAÇÃO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONSOLE DE DESPACHO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('BASE STATION','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('UPS','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RADIO PORTÁTIL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA FIXA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA MÓVEL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('GRAVADOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONVERSOR ELECTRO-ÓPTICO','24','SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/


