/* 
 * Table:	SERVICE_STATION
 */

INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE CCO'			,'SYSTEM');
INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE BARREIROS'		,'SYSTEM');
INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE VALONGO'		,'SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/

