/* 
 * Table:	SITES_TYPE
 */

INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CCO'						,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('LINHA'					,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('TERMINAL'				,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('TRECHO'					,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('VIA OU SENTIDO'			,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('ESTAÇÃO'					,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('PLATAFORMA'				,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA TÉCNICA'			,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('BASTIDOR'				,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SUB-ESTAÇÃO DE ENERGIA'	,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('MATERIAL RODANTE'		,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CRUZAMENTO'				,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA'					,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CABINE'					,'SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('EDIFÍCIO'				,'SYSTEM');

/** END OF TABLE POPULATION **/

