/* 
 * Table:	SITES_TYPE
 */

INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SUB-ESTAÇÃO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA TÉCNICA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('PLATAFORMA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('LINHA DE BLOQUEIO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('OFICINA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('ESTAÇÃO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('EDIFÍCIO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('PÁTIO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('TRECHO','SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/

