/* 
 * Table:	SUB_SYSTEM
 */

INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCF'	,'SISTEMA DE COMUNICAÇÃO FIXA'					,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCM'	,'SISTEMA DE COMUNICAÇÃO MÓVEL'					,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SSH'	,'SISTEMA DE SINCRONISMO HORÁRIO'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('STD'	,'SISTEMA DE TRANSMISSÃO DE DADOS'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SMM'	,'SISTEMA MULTIMÍDIA'							,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SME'	,'SISTEMA MONITORAÇÃO ELETRÔNICA'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCS'	,'SISTEMA DE CONTROLE SEMAFÓRICO'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCAP'	,'SISTEMA DE CONTROLE E ARRECAD DE PASSAGEIROS'	,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCT'	,'SISTEMA DE CONTROLE DE TRÁFEGO'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SIT'	,'SISTEMA DE IT'								,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SAE'	,'SISTEMA DE ALIMENTAÇÃO ELÉTRICA'				,'SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('PSD'	,'SISTEMA DE PORTAS DE PLATAFORMA'				,'SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/


