/* 
 * Table:	ALARMS_TYPE
 */

INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_SHOW_ALM, USR_INSERT)VALUES('FALHA DE COMUNICAÇÃO','Y','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_SHOW_ALM, USR_INSERT)VALUES('FALHA DE COMPONENTE ','Y','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_SHOW_ALM, USR_INSERT)VALUES('FALHA DE CONFIGURAÇÃO','Y','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_SHOW_ALM, USR_INSERT)VALUES('FALTA DE ALIMENTAÇÃO','Y','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_SHOW_ALM, USR_INSERT)VALUES('ESTADO DE EQUIPAMENTO','N','SYSTEM');

COMMIT;

/** END OF TABLE POPULATION **/

