/* 
 * Table:	ALARMS_TYPE
 */

INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('FALHA DE COMUNICAÇÃO','A','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('FALHA DE COMPONENTE ','A','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('FALHA DE CONFIGURAÇÃO','A','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('FALTA DE ALIMENTAÇÃO','A','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('ESTADO DE EQUIPAMENTO','C','SYSTEM');
INSERT INTO ALARMS_TYPE (ATY_DESCRIPTION, ATY_CLASS, USR_INSERT)VALUES('NORMALIZAÇÃO','A','SYSTEM');

/** END OF TABLE POPULATION **/

