--USUARIOS E CONFIGURACOES DE PERFIL
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('USER_CCO'		,'47bce5c74f589f4867dbd57e9ca9f808','ACTIVE',3);
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('USER_BASE_A'	,'47bce5c74f589f4867dbd57e9ca9f808','ACTIVE',4);
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('USER_BASE_B'	,'47bce5c74f589f4867dbd57e9ca9f808','ACTIVE',5);
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('USER_OPER_A'	,'47bce5c74f589f4867dbd57e9ca9f808','ACTIVE',6);
INSERT INTO USERS (USERNAME,PASSWORD,STATUS,ROLEID) VALUES ('USER_OPER_B'	,'47bce5c74f589f4867dbd57e9ca9f808','ACTIVE',7);


-- ACESSOS POR PERFIL
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) SELECT ID,1 FROM ROLE; --RECONHECER
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) SELECT ID,2 FROM ROLE; --NORMALIZAR

--facilita a vida na hora de fazer login colocando senha: aaa
UPDATE users SET password='47bce5c74f589f4867dbd57e9ca9f808' WHERE username = 'SYSTEM';

--BASES DE MANUTENCAO
INSERT INTO SERVICE_STATION(SST_ID, SST_DESCRIPTION,USR_INSERT) VALUES(1,'BASE A','JOABE');
INSERT INTO SERVICE_STATION(SST_ID, SST_DESCRIPTION,USR_INSERT) VALUES(2,'BASE B','JOABE');
SET GENERATOR GEN_SST_ID TO 2;


/** SETA DIREITOS USUARIO BASE A **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE A')
);

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE A')
);

/** SETA DIREITOS USUARIO BASE B **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE B')
);



INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE B')
);


/***********************************************************************/
/** SETA DIREITOS USUARIO OPERACAO (BASE A) **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE A)')
);


INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE A)')
);


/** SETA DIREITOS USUARIO OPERACAO (BASE B) **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE B)')
);


INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE B)')
);


INSERT INTO ROLE_SERVICES_STATIONS(roleId, stationId) SELECT ID ,1 FROM ROLE;
INSERT INTO ROLE_SERVICES_STATIONS(roleId, stationId) SELECT ID ,2 FROM ROLE;