/* Table:		EQUIPMENTS_MANUFACTURER
 * Prefix:		EMA
 * Date:		31/10/2014       
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE EQUIPMENTS_MANUFACTURER (
  EMA_ID INT NOT NULL PRIMARY KEY,
  EMA_DESCRIPTION VARCHAR(45) NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45) ,
  DTI_UPDATE TIMESTAMP);
COMMIT;

/*INDEXES*/
CREATE INDEX ix_EMA_INDEX1_idx ON EQUIPMENTS_MANUFACTURER(EMA_DESCRIPTION);

/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_EMA_ID;
SET GENERATOR GEN_EMA_ID TO 0;

/*CONSTRAINTS*/
ALTER TABLE EQUIPMENTS_MANUFACTURER
ADD CONSTRAINT uk_EMA_UNIQUE1 UNIQUE (EMA_DESCRIPTION);
COMMIT;

/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_EMA_ID  FOR EQUIPMENTS_MANUFACTURER ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.EMA_ID IS NULL)
        then new.EMA_ID = GEN_ID(GEN_EMA_ID,1);
END^
SET TERM ; ^
COMMIT;



/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_EMA_LOG  FOR EQUIPMENTS_MANUFACTURER ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

