/* Table:		SUB_SYSTEM
 * Prefix:		SSY
 * Date:		31/10/2014       
 * Author:		Joabe Lucena
 * References:	none
 * Obs:			Not Incremental ID
 * */

/*TABLE*/
CREATE TABLE SUB_SYSTEM (
  SSY_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  SSY_DESCRIPTION VARCHAR(45) NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45),
  DTI_UPDATE TIMESTAMP);
COMMIT;


/*INDEXES*/
CREATE INDEX ix_SSY_INDEX1_idx ON SUB_SYSTEM (SSY_DESCRIPTION);
  
  
/*REFERENCES*/

/*GENERATOR*/

/*TRIGGER ID*/


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_SSY_LOG  FOR SUB_SYSTEM ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

