/* Table:		DOCUMENTS
 * Prefix:		DOC
 * Date:		17/03/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE DOCUMENTS (
  DOC_ID			INT				NOT NULL,
  DOC_MODEL_ID		INT						,
  DOC_DESCRIPTION	VARCHAR(45) 	NOT NULL,
  DOC_URL			VARCHAR(100)	NOT NULL,
  USR_INSERT		VARCHAR(45)		NOT NULL,
  DTI_INSERT		TIMESTAMP		NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP,
  PRIMARY KEY (DOC_ID)
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_DOC_EMO_idx ON DOCUMENTS(DOC_MODEL_ID);

/*REFERENCES*/
ALTER TABLE DOCUMENTS
ADD CONSTRAINT fk_DOC_EMO_ref
    FOREIGN KEY (DOC_MODEL_ID)
    REFERENCES EQUIPMENTS_MODEL (EMO_ID);
    
/*GENERATOR*/
CREATE GENERATOR GEN_DOC_ID;
SET GENERATOR GEN_DOC_ID TO 0;

/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_DOC_ID  FOR DOCUMENTS ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.DOC_ID IS NULL)
        then new.DOC_ID = GEN_ID(GEN_DOC_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_DOC_LOG  FOR DOCUMENTS ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

