/* Table:		ALARMS_GROUP
 * Prefix:		AGR
 * Date:		03/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE ALARMS_GROUP (
  AGR_ID INT NOT NULL PRIMARY KEY,
  AGR_DESCRIPTION VARCHAR(45) NOT NULL,
  USR_INSERT VARCHAR(45) NOT NULL,
  DTI_INSERT TIMESTAMP NOT NULL,
  USR_UPDATE VARCHAR(45),
  DTI_UPDATE TIMESTAMP);
COMMIT;


/*INDEXES*/
CREATE INDEX ix_AGR_INDEX1_idx ON ALARMS_GROUP(AGR_DESCRIPTION);
  
  
/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_AGR_ID;
SET GENERATOR GEN_AGR_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_AGR_ID  FOR ALARMS_GROUP ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.AGR_ID IS NULL)
        then new.AGR_ID = GEN_ID(GEN_AGR_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_AGR_LOG  FOR ALARMS_GROUP ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

