/* Table:		ALARMS_TYPE
 * Prefix:		ATY
 * Date:		03/11/2014
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE ALARMS_TYPE (
  ATY_ID			INT			NOT NULL PRIMARY KEY,
  ATY_DESCRIPTION	VARCHAR(45) NOT NULL,
  ATY_SHOW_ALM		CHAR(1)		NOT NULL,
  USR_INSERT		VARCHAR(45) NOT NULL,
  DTI_INSERT		TIMESTAMP	NOT NULL,
  USR_UPDATE		VARCHAR(45),
  DTI_UPDATE		TIMESTAMP);
COMMIT;

/*INDEXES*/
CREATE INDEX ix_ATY_INDEX1_idx ON ALARMS_TYPE(ATY_DESCRIPTION);
  
/*REFERENCES*/

/*GENERATOR*/
CREATE GENERATOR GEN_ATY_ID;
SET GENERATOR GEN_ATY_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_ATY_ID  FOR ALARMS_TYPE ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.ATY_ID IS NULL)
        then new.ATY_ID = GEN_ID(GEN_ATY_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_ATY_LOG  FOR ALARMS_TYPE ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;


/******* END OF TABLE CONFIG *******/

