/* Table:		TASK_MONITOR_HEADER
 * Prefix:		TMH
 * Date:		09/06/2015
 * Author:		Joabe Lucena
 * References:	none
 * Obs:
 * */

/*TABLE*/
CREATE TABLE TASK_MONITOR_HEADER (
  TMH_ID		INT			NOT NULL PRIMARY KEY,
  TMH_DESC		VARCHAR(45)	NOT NULL,
  TMH_ACTIVE	CHAR(1)		NOT NULL,
  TMH_ALARM_ID	VARCHAR(40)	NOT NULL,
  USR_INSERT	VARCHAR(45)	NOT NULL,
  DTI_INSERT	TIMESTAMP	NOT NULL,
  USR_UPDATE	VARCHAR(45),
  DTI_UPDATE	TIMESTAMP
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_TMH_ALM_idx ON  TASK_MONITOR_HEADER(TMH_ALARM_ID);
  
/*REFERENCES*/
ALTER TABLE TASK_MONITOR_HEADER
ADD CONSTRAINT fk_TMH_ALM_ref
    FOREIGN KEY (TMH_ALARM_ID)
    REFERENCES ALARMS (ALM_ID);


/*GENERATOR*/
CREATE GENERATOR GEN_TMH_ID;
SET GENERATOR GEN_TMH_ID TO 0;


/*TRIGGER ID*/
SET TERM ^ ;
CREATE TRIGGER TRG_TMH_ID  FOR TASK_MONITOR_HEADER ACTIVE
BEFORE INSERT
AS
BEGIN
	if(new.TMH_ID IS NULL)
        then new.TMH_ID = GEN_ID(GEN_TMH_ID,1);
END^
SET TERM ; ^
COMMIT;


/*TRIGGER LOG*/
SET TERM ^ ;
CREATE TRIGGER TRG_TMH_LOG  FOR TASK_MONITOR_HEADER ACTIVE
BEFORE INSERT OR UPDATE
AS
BEGIN
	if(inserting)
        then new.DTI_INSERT = CURRENT_TIMESTAMP;
    if(updating)
        then new.DTI_UPDATE = CURRENT_TIMESTAMP;
END^
SET TERM ; ^
COMMIT;

/*** N:M RELATIONSHIP ***/
CREATE TABLE TASK_EQUIPMENT (
  TASK_ID		INT			NOT NULL,
  EQUIPMENT_ID	VARCHAR(20) NOT NULL,
  CUTOFF_DATE	TIMESTAMP,
  PRIMARY KEY (TASK_ID, EQUIPMENT_ID)
);
COMMIT;

/*INDEXES*/
CREATE INDEX fk_EQU_idx ON TASK_EQUIPMENT(EQUIPMENT_ID);
CREATE INDEX fk_THM_idx ON TASK_EQUIPMENT(TASK_ID);

/*REFERENCES*/
ALTER TABLE TASK_EQUIPMENT
ADD CONSTRAINT fk_THM_ref
    FOREIGN KEY (TASK_ID)
    REFERENCES TASK_MONITOR_HEADER (TMH_ID),
    
ADD CONSTRAINT fk_EQU_ref
    FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENTS (EQU_ID);
COMMIT;

/******* END OF TABLE CONFIG *******/

