/* 
 * Table:	EQUIPMENTS_TYPE
 */

INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ROUTER'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ACESSO'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('FIREWALL'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('TELEFONE IP'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SERVIDOR'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('STORAGE'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ESTAÇÃO DE TRABALHO'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RÁDIO PORTÁTIL'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONSOLE DE OPERAÇÃO'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ROTEADOR'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ESTAÇÃO BASE'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('NO-BREAK'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ANTENA RECEPTORA GPS'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PROTEÇÃO CONTRA RAIOS'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO MESTRE'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE DUPLA'	,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE SIMPLES'	,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL LED'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL TFT'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE PROJEÇÃO'		,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE CORNETA'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE TETO'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SENSOR DE RUÍDO'				,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MATRIZ DE ÁUDIO'				,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('INTERFACE DE I/O'				,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL LED'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MICROFONE MODULAR'				,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA FIXA'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA MÓVEL'					,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('GRAVADOR'						,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONVERSOR ELETRO-ÓTICO'			,'24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE CORNETA'			,'24','SYSTEM');


/** END OF TABLE POPULATION **/


