DELETE FROM ROLE_MENU;

INSERT INTO ROLE_MENU (MENUID, ROLEID) SELECT ID ,1 FROM MENU;

-- ACESSOS POR PERFIL
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) SELECT ID,1 FROM ROLE; --RECONHECER
INSERT INTO ROLE_FEATURES(ROLEID,FEATUREID) SELECT ID,2 FROM ROLE; --NORMALIZAR


/** SETA DIREITOS USUARIO BASE A **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE A')
);

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE A')
);

/** SETA DIREITOS USUARIO BASE B **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE B')
);

INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'BASE B')
);


/***********************************************************************/
/** SETA DIREITOS USUARIO OPERACAO (BASE A) **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE A)')
);


INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE A)')
);


/** SETA DIREITOS USUARIO OPERACAO (BASE B) **/
INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Inicio' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE B)')
);


INSERT INTO ROLE_MENU (MENUID, ROLEID)VALUES(
	(SELECT ID FROM MENU WHERE TEXT = 'Ordem de Serviço' AND PARENT_ID IS NULL),
	(SELECT ID FROM ROLE WHERE ROLENAME = 'OPERACAO (BASE B)')
);
