/** RUN THE RESULT OF THIS QUERY FOR DROP ALL DATABASE ITENS **/

-- FOREIGN KEYS
SELECT
	'ALTER TABLE '||TRIM(RDB$RELATION_NAME)||' DROP CONSTRAINT '||TRIM(RDB$CONSTRAINT_NAME) || ';'
FROM RDB$RELATION_CONSTRAINTS

WHERE RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
UNION ALL
-- TABELAS
SELECT 'DROP TABLE ' || TRIM(RDB$RELATION_NAME) ||';' FROM RDB$RELATIONS WHERE RDB$FLAGS IS NOT NULL
UNION ALL
--GENERATORS
SELECT 'DROP GENERATOR '|| TRIM(RDB$GENERATOR_NAME) || ';' FROM RDB$GENERATORS WHERE RDB$SYSTEM_FLAG = 0
UNION ALL
--COMMIT
SELECT 'COMMIT;' FROM RDB$DATABASE;