-- Tabela: Sites Type

INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CCO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('LINHA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('TERMINAL','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('TRECHO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('VIA OU SENTIDO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('ESTAÇÃO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('PLATAFORMA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA TÉCNICA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('BASTIDOR','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SUB-ESTAÇÃO DE ENERGIA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('MATERIAL RODANTE','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CRUZAMENTO','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('SALA','SYSTEM');
INSERT INTO SITES_TYPE (STY_DESCRIPTION,USR_INSERT)VALUES('CABINE','SYSTEM');

-- Tabela: Service Station

INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE CCO','SYSTEM');
INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE BARREIROS','SYSTEM');
INSERT INTO SERVICE_STATION (SST_DESCRIPTION,USR_INSERT)VALUES('BASE VALONGO','SYSTEM');

-- Tabela: Sites

INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'CENTRO DE CONTROLE OPERACIONAL', 
        'CCO',
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'),
        NULL,
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'CCO'),
        'SYSTEM'
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'TRECHO BARREIROS-PORTO',                                            --DESCRICAO
        'TBP',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        NULL,                                                                --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'LINHA'),         --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'TRECHO CONSELHEIRO NÉBIAS-VALONGO',                                 --DESCRICAO
        'TCV',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        NULL,                                                                --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'LINHA'),        --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'PÁTIO PORTO',                                                       --DESCRICAO
        'PPO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        NULL,                                                                --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'TERMINAL'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );

INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'TERMINAL PORTO',                                                --DESCRICAO
        'POR',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'CONSELHEIRO NÉBIAS',                                                --DESCRICAO
        'ABU',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'WASHINGTON LUÍS',                                                --DESCRICAO
        'WLU',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'ANA COSTA',                                                --DESCRICAO
        'ANA',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'BERNADINO DE CAMPOS',                                                --DESCRICAO
        'BCA',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'ORQUIDÁRIO',                                                --DESCRICAO
        'ORQ',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'PINHEIRO MACHADO',                                                --DESCRICAO
        'PMA',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'NOSSA SENHORA DE LOURDES',                                                --DESCRICAO
        'NSL',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'JOÃO RIBEIRO',                                                --DESCRICAO
        'JRI',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'ITARARÉ',                                                          --DESCRICAO
        'ITR',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'JOSÉ MONTEIRO',                                                --DESCRICAO
        'JMO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'NOSSA SENHORA DAS GRAÇAS',                                                --DESCRICAO
        'NSG',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'ANTÔNIO EMMERICH',                                                --DESCRICAO
        'AEM',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SÃO VICENTE',                                                --DESCRICAO
        'SVI',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'MASCARENHAS DE MORAIS',                                                --DESCRICAO
        'MMO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'BARREIROS',                                                        --DESCRICAO
        'BAR',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'JOÃO GUERRA',                                                        --DESCRICAO
        'JGU',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'UNIVERSIDADES I',                                                        --DESCRICAO
        'UN1',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'MERCADO',                                                        --DESCRICAO
        'MCD',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'POUPATEMPO',                                                        --DESCRICAO
        'PPA',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'MAUÁ',                                                        --DESCRICAO
        'MAU',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SÃO BENTO',                                                        --DESCRICAO
        'SBE',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'VALONGO',                                                        --DESCRICAO
        'VAL',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'JOSÉ BONIFÁCIO',                                                    --DESCRICAO
        'JBO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'BITTENCOURT',                                                        --DESCRICAO
        'BTC',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'RANGEL PESTANA',                                                        --DESCRICAO
        'RPE',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'UNIVERSIDADES II',                                                        --DESCRICAO
        'UN2',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'TAMANDARÉ',                                                        --DESCRICAO
        'TMD',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'ESTAÇÃO'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO TERMINAL BARREIROS',                                                        --DESCRICAO
        'SEBAR',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO MASCARENHAS DE MORAIS',                                                        --DESCRICAO
        'SEMMO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO ANTÔNIO EMMERICH',                                                        --DESCRICAO
        'SEAEM',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO JOSÉ MONTEIRO',                                                        --DESCRICAO
        'SEJMO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO NOSSA SENHORA DE LOURDES',                                                        --DESCRICAO
        'SENSL',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO BERNADINO DE CAMPOS',                                                        --DESCRICAO
        'SEBCA',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO WASHINGTON LUÍS',                                                        --DESCRICAO
        'SEWLU',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO TERMINAL PORTO',                                                        --DESCRICAO
        'SEPPO',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TBP'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO UNIVERSIDADE',                                                        --DESCRICAO
        'SEUN1',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO AMADOR BUENO',                                                        --DESCRICAO
        'SEUN1',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
INSERT INTO SITES (SIT_DESCRIPTION,SIT_SHORTNAME,SIT_STATION_ID,SIT_PARENT_ID,SIT_TYPE_ID,USR_INSERT)
VALUES(
        'SUB-ESTAÇÃO VALONGO',                                                        --DESCRICAO
        'SEVAL',                                                               --SIGLA
        (SELECT SST_ID FROM SERVICE_STATION WHERE SST_DESCRIPTION = 'BASE CCO'), --BASE DE MANUTENÇÃO
        (SELECT SIT_ID FROM SITES WHERE SIT_SHORTNAME = 'TCV'),                  --PAI/PARENT
        (SELECT STY_ID FROM SITES_TYPE WHERE STY_DESCRIPTION = 'SUB-ESTAÇÃO DE ENERGIA'),      --TIPO DE LOCAL
        'SYSTEM'                                                             --USUÁRIO
    );
    
--Tabela: SUB_SYSTEM

INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCF','SISTEMA DE COMUNICAÇÃO FIXA','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCM','SISTEMA DE COMUNICAÇÃO MÓVEL','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SSH','SISTEMA DE SINCRONISMO HORÁRIO','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('STD','SISTEMA DE TRANSMISSÃO DE DADOS','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SMM','SISTEMA MULTIMÍDIA','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SME','SISTEMA MONITORAÇÃO ELETRÔNICA','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCS','SISTEMA DE CONTROLE SEMAFÓRICO','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCAP','SISTEMA DE CONTROLE E ARRECAD DE PASSAGEIROS','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SCT','SISTEMA DE CONTROLE DE TRÁFEGO','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('SAE','SISTEMA DE ALIMENTAÇÃO ELÉTRICA','SYSTEM');
INSERT INTO SUB_SYSTEM (SSY_ID,SSY_DESCRIPTION,USR_INSERT)VALUES('PSD','SISTEMA DE PORTAS DE PLATAFORMA','SYSTEM');

--Tabela: EQUIPMENTS_PROTOCOL
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv1','SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv2c','SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('SNMPv3','SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES SOAP 1.1','SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES JSON','SYSTEM');
INSERT INTO EQUIPMENTS_PROTOCOL (EPR_DESCRIPTION,USR_INSERT)VALUES('WEBSERVICES SOAP MAESTRO','SYSTEM');

--Tabela: EQUIPMENTS_MANUFACTURER

INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('TTRANS SISTEMAS','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('DELL','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('BROCADE','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('WESTERSTRAND','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('SEPURA','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('IBM','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('LENOVO','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('HP','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('GTEC','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('SIEMENS','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('REDBOX','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('HUAWEI','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('AFINA','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('THALES','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('SCHNEIDER ELECTRIC','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('PENTON','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('ASL','SYSTEM');
INSERT INTO EQUIPMENTS_MANUFACTURER (EMA_DESCRIPTION,USR_INSERT)VALUES('MICROPROCESSADOR','SYSTEM');

--Tabela: EQUIPMENTS_TYPE

INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ROUTER','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SWITCH ACESSO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('FIREWALL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('TELEFONE IP','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SERVIDOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('STORAGE','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ESTAÇÃO DE TRABALHO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RÁDIO PORTÁTIL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONSOLE DE OPERAÇÃO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ROTEADOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ESTAÇÃO BASE','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('NO-BREAK','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ANTENA RECEPTORA GPS','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PROTEÇÃO CONTRA RAIOS','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO MESTRE','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE DUPLA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('RELÓGIO DIGITAL - FACE SIMPLES','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL LED','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL TFT','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE PROJEÇÃO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE CORNETA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE TETO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('SENSOR DE RUÍDO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MATRIZ DE ÁUDIO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('INTERFACE DE I/O','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('PAINEL LED','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('MICROFONE MODULAR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA FIXA','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CÂMERA MÓVEL','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('GRAVADOR','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('CONVERSOR ELETRO-ÓTICO','24','SYSTEM');
INSERT INTO EQUIPMENTS_TYPE (ETY_DESCRIPTION,ETY_DAILY_HOURS,USR_INSERT)VALUES('ALTOFALANTE DE CORNETA','24','SYSTEM');

--Tabela: EQUIPMENTS_MODEL

INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS OPENSTAGE 15',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS DIUT2',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS STMI4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS PSU',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS LUNA',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SIEMENS DSCXL2',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('SEPURA SOLO',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HP ML350pGen8',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('CISCO 2911',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('GTEC AK-160N',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND QW-TIME III',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND LUMEX 7',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND E591B',NULL,'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('WESTERSTRAND ESP30D/2BX',NULL,'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HUAWEI S7703',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('HUAWEI S5700-28C-PWR-SI',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('FORTIGATE 100 D',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IBM x3250 M4',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('IBM v3700',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('LENOVO ThinkCentre m73e SFF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv2c'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('MICROPROCESSADOR PPP.8.96A9RDF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('MICROPROCESSADOR PPP.TFT.32.A2.SF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON CAD10/TEN',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON RCS5FT/ENC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('PENTON PH20/TC',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL ANS04',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL iPA400',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL BMB01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('ASL MPS01',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'SNMPv1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-2CD893PF-E',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-2DF1-514',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES TH-9616NI-ST',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('THALES DS-3D01R-A',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP MAESTRO'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS BLOQUEIO TRIPE SMART BTS',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS BE ESPECIAL FLAP BEF',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');
INSERT INTO EQUIPMENTS_MODEL (EMO_DESCRIPTION,EMO_PROTOCOL_ID,USR_INSERT)VALUES('TTRANS DCE FLAP SMART DCFS',(SELECT EPR_ID FROM EQUIPMENTS_PROTOCOL WHERE EPR_DESCRIPTION = 'WEBSERVICES SOAP 1.1'),'SYSTEM');




